stages:
- name: Codeception test
  steps:
  - runScriptConfig:
      image: node:8
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ironbane:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: deployment.yaml