kind: Service
apiVersion: v1
metadata:
  name: ironbane-service
spec:
  selector:
    app: ironbane
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironbane
  labels:
    app: ironbane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ironbane
  template:
    metadata:
      labels:
        app: ironbane
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: ironbane
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8000